### ISSUE TITLE
Proposal: provide alternative to FCM using Serverpod

### ISSUE THREAD

**Issue by lukehutch** [ben-xD/push#17]
Serverpod proposes to add its own push messaging solution: https://github.com/serverpod/serverpod/issues/439

I would love to see a solution for Android that doesn't require FCM, but instead pairs your `push` library with Serverpod as the push notification server.

Do you have any interest in working on something like that, or potentially collaborating on this project?

I can probably contribute some work on Serverpod, but I don't know the client side of push notifications.

**Comment by ben-xD** [comment]
Hey @lukehutch, I don't think it is viable to compete with FCM on Android, because of Android's restrictions/limitations. Serverpod could use UnifiedPush, but Android apps would need a persistent notification (forever showing) in the notification tray. I suspect this is unacceptable for most apps, so it's a feature that's not worth doing.

I hope UnifiedPush progresses though, but IMHO Google and Android has full control over it's fate on vanilla Android.

This might still be useful feature for Android forks though, like LineageOS. In that case we would need to add support for UnifiedPush in this package.

**Comment by lukehutch** [comment]
@ben-xD There is also Web Push, which should get around this limitation of UnifiedPush. However a Flutter app would have to add a JS service worker. I'm not sure how easy that is, but I'll take a look.

**Comment by ben-xD** [comment]
Unfortunately that would not change anything. Browsers implement web push using APNs (e.g. Safari on iOS https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/ and FCM on Android.

iOS:
> Web Push on iOS and iPadOS uses the same Apple Push Notification service that powers native push on all Apple devices. 

Firefox, on iOS and Android https://mozilla-services.github.io/autopush-rs/install.html#configuring-for-third-party-bridge-services
> How we connect and use these systems is described in the following documents:

    Apple Push Notification service (APNs)
    Google's Fire Cloud Messaging service (FCM)

Sure you could send notifications to your web app, but that wouldnt reach your flutter app. Certainly won't be able to communicate freely between your web app and Flutter app.

**Comment by ben-xD** [comment]
I'll close this for now as I don't think it's actionable due to the limitations I mentioned.
